### ISSUE TITLE
No license!

### ISSUE THREAD

**Issue by trdarr** [iambrianchan/bevmo-5cent-wines#3]
From https://blog.codinghorror.com/pick-a-license-any-license/:

> Because I did not explicitly indicate a license, I declared an implicit copyright without explaining how others could use my code. Since the code is unlicensed, I could theoretically assert copyright at any time and demand that people stop using my code. Experienced developers won't touch unlicensed code because they have no legal right to use it. That's ironic, considering the whole reason I posted the code in the first place was so other developers could benefit from that code. I could have easily avoided this unfortunate situation if I had done the right thing and included a software license with my code.

GitHub has made it really easy, also: [http://choosealicense.com/]().

**Comment by iambrianchan** [comment]
Added a license.
